window.TCC_DATA = {
  "datas": {
    "22/10/2025": [
      {
        "data": "22/10/2025",
        "hora": "08:30",
        "aluno": "Agda da Silva de Paula",
        "titulo": "Uma Proposta de Ontologia no Domínio do Câncer \nde mama com enfoque nos fatores de risco",
        "orientador": "Cristiano",
        "revisor1": "Flavio",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "09:00",
        "aluno": "Leonardo Rodrigues Cavalcante",
        "titulo": "Automação do Acesso a Informações de \nMedicamentos: Proposta de um Chatbot Baseado \nem Evidências Científicas",
        "orientador": "Cristiano",
        "revisor1": "Flavio",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "09:30",
        "aluno": "Yuri Pessanha Ribeiro Gomes Carneiro",
        "titulo": "Geração Automática de Questões para Certificação \nde Árbitros de Triathlon com Processamento de \nLinguagem Natural: Um Estudo Aplicado ao \nRegulamento da World Triathlon",
        "orientador": "Cristiano",
        "revisor1": "Flavio",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "10:00",
        "aluno": "Bianca da Silva Rodrigues",
        "titulo": "Linguagem Natural: Um Estudo Aplicado ao Regulamento da World Triathlon",
        "orientador": "Cristiano",
        "revisor1": "Flavio",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "10:30",
        "aluno": "Cristiano",
        "titulo": "A definir",
        "orientador": "Cristiano",
        "revisor1": "Cristiano",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "11:00",
        "aluno": "Helio  Breda Netto",
        "titulo": "Rastreamento  de Cadeia de Suprimentos Agricolas Usando a Tecnologia Blockchain",
        "orientador": "João Paulo",
        "revisor1": null,
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "11:30",
        "aluno": "Pedro Gomes",
        "titulo": "GERENCIADOR DE EFICIÊNCIA DE PRODUÇÃO EM PLACAS SOLARES COM SOLUÇÃO BLOCKCHAIN PARA NEGOCIAÇÃO DE EXCEDENTES",
        "orientador": "João Paulo",
        "revisor1": null,
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "12:00",
        "aluno": "Pedro Henrique Braido",
        "titulo": "UMA SOLUÇÃO PARA AUXILIAR NA MOBILIDADE URBANA - SISTEMA DE CARONAS INTEGRADO COM BLOCKCHAIN",
        "orientador": "João Paulo",
        "revisor1": null,
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "15:00",
        "aluno": "Gabriel Barboza Sarte",
        "titulo": "Shadow AI no desenvolvimento de software: Proposta de plataforma para capacitação segura em ia generativa",
        "orientador": "Susana",
        "revisor1": "Rafael V",
        "revisor2": "Ricardo",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "15:30",
        "aluno": "Bruna Ribeiro Cedro",
        "titulo": "SISTEMA INTELIGENTE DE RECOMENDAÇÃO DE INVESTIMENTO BASEADO EM REDES NEURAIS",
        "orientador": "Susana",
        "revisor1": "Rafael V",
        "revisor2": "Ricardo",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "16:00",
        "aluno": "Gabriel Rosaes",
        "titulo": "Desenvolvimento de um Sistema Inteligente para Monitoramento e Segurança em Rodovias Utilizando Visão Computacional",
        "orientador": "Ricardo",
        "revisor1": "Rafael V",
        "revisor2": "Susana",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "16:30",
        "aluno": "Gabriel Louzada da Silva",
        "titulo": "Análise de Toxicidade e Linguagem Inapropriada em Conteúdos Infantis",
        "orientador": "Rafael V",
        "revisor1": "Ricardo",
        "revisor2": "Susana",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "22/10/2025",
        "hora": "17:00",
        "aluno": "Luis Henrique Cabral Zanella",
        "titulo": "Utilização de Redes Neurais para Previsão de Vida Útil Remanescente de Equipamentos",
        "orientador": "Rafael V",
        "revisor1": "Ricardo",
        "revisor2": "Susana",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      }
    ],
    "23/10/2025": [
      {
        "data": "23/10/2025",
        "hora": "08:00",
        "aluno": "João Paulo Gueller Azevedo",
        "titulo": "Aplicação de Rag na Consulta de Editais dos \nCursos Técnicos Integrados ao Ensino Médio do \nIfes - Campus Cachoeiro de Itapemirim",
        "orientador": "Cristiano",
        "revisor1": "Flavio",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "08:30",
        "aluno": "Fernanda de Oliveira Ramos",
        "titulo": "Uma Abordagem Híbrida para o Reconhecimento de \nEntidades Nomeadas em Relatos de Casos Clínicos",
        "orientador": "Cristiano",
        "revisor1": "Flavio",
        "revisor2": "Rafael G",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "09:00",
        "aluno": "João Victor de Salles Mapeli Couzzi",
        "titulo": "Classificação de Sentimentos em Conteúdos Infantis do YouTube com a Abordagem Baseada em Modelos de Processamento de Linguagem Natural",
        "orientador": "Rafael V",
        "revisor1": "Flavio",
        "revisor2": "Rafael G",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "09:30",
        "aluno": "Mateus de Angeli Almeida",
        "titulo": "Otimização de Carteiras de Investimentos com Algoritmos Genéticos: Uma Abordagem para a Estratégia Buy and Hold",
        "orientador": "Rafael V",
        "revisor1": "Flavio",
        "revisor2": "Lucas Poubel",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "10:00",
        "aluno": "Eduardo Rodrigues Almeida",
        "titulo": "APLICAÇÃO DE APRENDIZADO DE MÁQUINA PARA CLASSIFICAÇÃO DE FLUXOS DE REDES EM DISPOSITIVOS SD-WAN",
        "orientador": "Rafael G",
        "revisor1": "Everson",
        "revisor2": "Bruno",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "10:30",
        "aluno": "Pedro Lucas Brito Moreira",
        "titulo": "REDES NEURAIS CONVOLUCIONAIS PARA SEGMENTAÇÃO E CLASSIFICAÇÃO DE ROCHAS ORNAMENTAIS",
        "orientador": "Rafael G",
        "revisor1": "Juliano",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "11:00",
        "aluno": "Welington Gulinelli",
        "titulo": "COMPARAÇÃO DOS PLANOS DE DADOS P4EMU E XDP DO SOFTWARE SWITCH\nFREERTR PARA REDES DEFINIDAS POR SOFTWARE (SDN)",
        "orientador": "Everson",
        "revisor1": "Rafael G",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "11:30",
        "aluno": "RAFAEL LACERDA DO AMPARO GOMES",
        "titulo": "TECNOLOGIAS EDUCACIONAIS: O USO DA GAMIFICAÇÃO COMO FERRAMENTA DE APOIO À ALFABETIZAÇÃO DE JOVENS E ADULTOS",
        "orientador": "Emanoel",
        "revisor1": "Bruno",
        "revisor2": null,
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      },
      {
        "data": "23/10/2025",
        "hora": "13:30",
        "aluno": "Marcelo",
        "titulo": null,
        "orientador": "Susana",
        "revisor1": "Emanoel",
        "revisor2": "Bruno",
        "nota_orientador": 0.0,
        "nota_revisor1": 0.0,
        "nota_revisor2": 0.0,
        "media_total": 0.0
      }
    ]
  },
  "gerado_em": "2025-10-20 22:10:04"
};
