name: Build data.js from CSVs

permissions:
  contents: write

on:
  push:
    paths:
      - 'data/*.csv'
      - 'build_data.py'
      - '.github/workflows/build-data.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install pandas

      - name: Build data.js
        run: python build_data.py

      - name: Commit data.js
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data.js
          git commit -m "chore: rebuild data.js from CSVs" || echo "no changes"
          git push
